# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = [ "g", "." ]
run = "cd ~/.dotfiles"
desc = "Go ~/dotfiles"
